version: "3.5"
services:
  webserver:
    build: 
      context: './services_conf/website/'
    volumes:
      - ./services_depl/public_html/:/var/www/html/
    container_name: webserver
    depends_on:
      - db_service
    expose:
      - "80"
    ports:
      - "80:80"
    networks:
      default:
        ipv4_address: 172.18.1.9
  db_service:
    build: 
      context: './services_conf/db_service/'
    volumes:
      - ./services_depl/db_app:/var/www/html/
    container_name: db_service
    depends_on:
      - mysql-db
    ports:
      - "8090:80"
    networks:
      default:
        ipv4_address: 172.18.1.4
  db-proxy:
    image: fiware/pep-proxy
    container_name: fiware-db-proxy
    hostname: db-proxy
    networks:
        default:
            ipv4_address: 172.18.1.16
    depends_on:
        - keyrock
        - authzforce
    ports:
        - "8095:8095"
    expose:
        - "8095"
    environment:
        - PEP_PROXY_APP_HOST=db_service
        - PEP_PROXY_APP_PORT=80
        - PEP_PROXY_PORT=8095
        - PEP_PROXY_IDM_HOST=keyrock
        - PEP_PROXY_HTTPS_ENABLED=false
        - PEP_PROXY_IDM_SSL_ENABLED=false
        - PEP_PROXY_IDM_PORT=3000
        - PEP_PROXY_APP_ID=ad817d0b-35c7-4497-ad7c-896629aa1879
        - PEP_PROXY_USERNAME=pep_proxy_1d18abfb-e8bd-44ab-bedc-3f53d855d7c1
        - PEP_PASSWORD=pep_proxy_5ce16ff2-c25f-4b25-8aae-c909ad63ed1f
        - PEP_PROXY_PDP=authzforce
        - PEP_PROXY_AUTH_ENABLED=true
        - PEP_PROXY_MAGIC_KEY=thismagickeyfordb
        - PEP_PROXY_AZF_PROTOCOL=http
        - PEP_PROXY_AZF_HOST=authzforce
        - PEP_PROXY_AZF_PORT=8080
  mysql-db:
    image: mysql:5.7
    restart: always
    hostname: mysql-db
    container_name: mysql-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 172.18.1.6
    environment:
      - "MYSQL_ROOT_PASSWORD=rootpassword"
      - "MYSQL_ROOT_HOST=172.18.1.5"
    volumes:
      - data2:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: rootpassword 
    networks:
      default:
        ipv4_address: 172.18.1.7
    container_name: phpmyadmin
  keyrock:
    image: fiware/idm
    container_name: fiware-keyrock
    hostname: keyrock
    networks:
      default:
        ipv4_address: 172.18.1.5
    depends_on:
      - mysql-db
      - authzforce
    ports:
      - "3000:3000"
      - "443:443"
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql-db
      - IDM_HOST=http://localhost:3000
      - IDM_PORT=3000
        # Development use only
        # Use Docker Secrets for Sensitive Data
      - IDM_DB_PASS=rootpassword
      - IDM_DB_USER=root
      - IDM_ADMIN_USER=pgiannakopoulos1
      - IDM_ADMIN_EMAIL=pgiannakopoulos1@isc.tuc.gr
      - IDM_ADMIN_PASS=1234
      - IDM_PDP_LEVEL=advanced
      - IDM_AUTHZFORCE_ENABLED=true
      - IDM_AUTHZFORCE_HOST=authzforce
      - IDM_AUTHZFORCE_PORT=8080
  authzforce:
    image:  fiware/authzforce-ce-server:release-8.1.0
    hostname: authzforce
    container_name: fiware-authzforce
    networks:
        default:
            ipv4_address: 172.18.1.19
    ports:
        - "9090:8080"
    volumes:
        - ./authzforce/domains:/opt/authzforce-ce-server/data/domains
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes:
  data2:
