version: "3.1"
services:
  webserver:
    build: 
      context: './webserver/'
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: webserver
    depends_on:
      - db_service
    ports:
      - "80:80"
  db_service:
    build: 
      context: './webserver/'
    volumes:
      - ./db_app:/var/www/html/
    container_name: db_service
    depends_on:
      - db
    ports:
      - "8090:80"
    networks:
       - db_network
  db:
    build:
      context: './mysql/'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data2:/var/lib/mysql
    networks:
      - db_network
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword 
    networks:
      - db_network
    container_name: phpmyadmin
networks:
  db_network:
volumes:
  data2:
